[package]
name = "rome"
version = "0.1.1"
authors = ["Jos van den Oever <jos@vandenoever.info>"]
license = "AGPL-3.0"
description = "An RDF library in pure Rust"
homepage = "https://github.com/vandenoever/rome"
repository = "https://github.com/vandenoever/rome"
documentation = "https://www.vandenoever.info/rust/rome/"

[dependencies]
# for the library
lazy_static = "0.2.2"
nom = "^2"
rand = "0.3.15"
regex = "0.2.1"

# for the examples
time = "0.1.36"

[features]
default = []

# Unstable parts of this crate are hidden behind this feature.
# There are no API guarantees for the functionality exposed by this feature.
unstable = []
